version: '3'
services:
  cms:
    build:
      context: ./bytez-admin
      dockerfile: Dockerfile
    container_name: cms
    env_file:
      - ./bytez-admins/.env.prod
    ports:
      - '1337:1337'
    networks:
      - main-net
    depends_on:
      - postgres

  landing:
    build:
      context: ./bytze
      dockerfile: Dockerfile
    container_name: landing
    ports:
      - 3000:3000
    networks:
      - main-net
    env_file:
      - ./bytze/.env.prod

  postgres:
    image: postgres
    container_name: database
    networks:
      - main-net
    environment:
      POSTGRES_DB: <POSTGRES_DB>
      POSTGRES_USER: <POSTGRES_USER>
      POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    depends_on:
      - <serivce>
      - <database>
    networks:
      - main-net
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:1337 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      ALLOWED_DOMAINS: ([a-z]+.)?archeryburnfire.vn
      SITES: '<subdomain>=<service>:<port>;<domain>=<service>:<port>;'

volumes:
  pgdata:
  ssl_data:

networks:
  main-net:
    external: true
    driver: bridge
